services:
  postgres-dev:
    restart: always
    image: postgres:14.3
    environment:
      TZ: "Etc/GMT-0"
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - orion

networks:
  orion:
    driver: bridge
