services:
  postgres-test:
    restart: always
    image: postgres:14.3
    environment:
      TZ: GMT
      PGTZ: GMT
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    command: ["postgres", "-c", "timezone=GMT"]
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./init-test.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - orion

networks:
  orion:
    driver: bridge
