services:
  satisfacao-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    environment:
      NODE_ENV: prod
      TZ: ${TZ}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}
    volumes:
      - .:/usr/src/app
    restart: always
    env_file:
      - .env.prod
    networks:
      - orion

networks:
  orion:
    driver: bridge
